name: Danger

on:
  pull_request:
    types: [synchronize, opened, reopened, edited]

jobs:
  build:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }} # Only run on non-forked PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn install
      - name: Install danger
        run: yarn global add danger
      - name: Validate PR title validation rules
        working-directory: ./ci/validate-pr-title
        run: node validate.test.js
      - name: Danger
        run: danger ci
        working-directory: ./ci/validate-pr-title
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
